server.port=8096
spring.application.name=order-service

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://127.0.0.1:9411/api/v2/spans
logging.pattern.level=%5p [traceId=%X{traceId}, spanId=%X{spanId}]
